apiVersion: v2
name: ingress-nginx-free-oracle-nlb
description: A Helm chart that extends ingress-nginx with Oracle Cloud annotations
version: 0.1.0

dependencies:
  - name: ingress-nginx
    version: 4.11.3
    repository: "https://kubernetes.github.io/ingress-nginx"