ingress-nginx:
  controller:
    service:
      annotations:
        oci.oraclecloud.com/load-balancer-type: "nlb"
  namespaceOverride: ingress-nginx-free-oracle-nlb
namespace: ingress-nginx-free-oracle-nlb