argo-cd:
  crds:
    install: true
    keep: false
  namespaceOverride: oci-argo-cd
  global:
    domain: argocd.ricardllop.com
  server:  
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-redirect-from: "http"
        nginx.ingress.kubernetes.io/proxy-redirect-to: "https"
      hostname: argocd.ricardllop.com
      tls:
        - hosts:
            - argocd.ricardllop.com
          secretName: argocd-tls